resolver: lts-24.30

system-ghc: true
install-ghc: false

packages:
- .

ghc-options:
  pdeprelude: -haddock

extra-deps:
# UNCOMMENT ME - git: https://github.com/uqbar-project/pdepreludat.git
# UNCOMMENT ME   commit: REPLACE WITH CURRENT COMMIT

- ../ # REMOVE THIS LINE
